---
# tasks file for gitlab
- name: Install
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - ca-certificates
    - curl
    - openssh-server
    - postfix

- name: Download GitLab
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
    dest: /tmp/script.deb.sh

- name: bash download gitlab
  command: bash /tmp/script.deb.sh

- name: Install
  package:
    name: gitlab-ce
    state: present
  async: 500
  poll: 5

- name: replace url
  ansible.builtin.lineinfile:
    path: /etc/gitlab/gitlab.rb
    search_string: 'external_url ''http://gitlab.example.com'''
    line: 'external_url ''http://gitlab.{{ domain }}'''

- name: replace password
  ansible.builtin.lineinfile:
    path: /etc/gitlab/gitlab.rb
    search_string: '# gitlab_rails[''initial_root_password''] = "password"'
    line: 'gitlab_rails[''initial_root_password''] = "{{ gitlab_password }}"'

- name: replace token
  ansible.builtin.lineinfile:
    path: /etc/gitlab/gitlab.rb
    search_string: '# gitlab_rails[''initial_shared_runners_registration_token''] = "token"'
    line: 'gitlab_rails[''initial_shared_runners_registration_token''] = "{{ gitlab_token }}"'

- name: reconfigure gitlab
  command: gitlab-ctl reconfigure
  register: gitlab_restart
  failed_when: gitlab_restart.rc != 0 | bool
