---
# tasks file for monitoring
# grafana
- name: add gpg key grafana
  ansible.builtin.shell: wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -

- name: add repository grafana
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/enterprise/deb stable main

- name: Install
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - grafana-enterprise

- name: start service
  ansible.builtin.service:
    name: grafana-server
    enabled: yes
    state: started



# prometheus
- name: Create group
  group:
    name: prometheus
    system: true

- name: Create service user
  user:
    name: prometheus
    create_home: no
    shell: "/bin/false"
    group: prometheus

- name: download prometheus
  unarchive:
#    src: https://github.com/prometheus/prometheus/releases/download/v2.36.2/prometheus-2.36.2.linux-amd64.tar>
    src: "https://github.com/prometheus/prometheus/releases/download/v2.38.0-rc.0/prometheus-2.38.0-rc.0.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
    validate_certs: no

- name: Create directory
  file:
    name: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  with_items:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Copy files
  copy:
    src: /tmp/prometheus-2.38.0-rc.0.linux-amd64/{{ item }}
    dest: /usr/local/bin/
    remote_src: yes
    mode: preserve
    owner: prometheus
    group: prometheus
  with_items:
    - 'prometheus'
    - 'promtool'

- name: Copy files
  copy:
    src: /tmp/prometheus-2.38.0-rc.0.linux-amd64/{{ item }}
    dest: /etc/prometheus
    remote_src: yes
    mode: preserve
    owner: prometheus
    group: prometheus
  with_items:
    - 'console_libraries'
    - 'consoles'
    - 'prometheus.yml'

- name: Create service
  template:
    src: templates/prometheus.service
    dest: /etc/systemd/system/

- name: Reload daemon systemd
  systemd:
    daemon_reload: yes

- name: Copy config files
  template:
    src: templates/{{ item }}
    dest: /etc/prometheus/
  with_items:
    - 'prometheus.yml'
    - 'alert.yml'

- name: Start service
  systemd:
    name: prometheus
    state: started
    enabled: yes

 #alertmanager

- name: Create group
  group:
    name: alertmanager
    system: true
    state: present

- name: Create service user
  user:
    name: alertmanager
    create_home: no
    shell: "/bin/false"
    group: prometheus

- name: Create directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
  with_items:
    - '/tmp/alertmanager'
    - '/etc/alertmanager'
    - '/var/lib/prometheus/alertmanager'

- name: Download source files
  become: true
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.24.0/alertmanager-0.24.0.linux-amd64.tar.gz
    dest: /tmp/alertmanager
    creates: /tmp/alertmanager/alertmanager-0.24.0.linux-amd64
    remote_src: yes

- name: Copy source files
  become: true
  copy:
    src: /tmp/alertmanager/alertmanager-0.24.0.linux-amd64/{{ item }}
    dest: /usr/local/bin/
    remote_src: yes
    mode: preserve
    owner: alertmanager
    group: alertmanager
  with_items:
    - 'alertmanager'
    - 'amtool'

- name: Copy config file
  become: true
  copy:
    src: /tmp/alertmanager/alertmanager-0.24.0.linux-amd64/alertmanager.yml
    dest: /etc/alertmanager/
    remote_src: yes
    mode: preserve
    owner: alertmanager
    group: alertmanager

- name: Create systemd service
  become: true
  template:
    src: templates/alertmanager.service
    dest: /etc/systemd/system/

- name: Reload systemd
  become: true
  systemd:
    daemon_reload: yes

- name: Start service
  become: true
  systemd:
    name: alertmanager
    state: started
    enabled: yes
