---

  - hosts: nodes
    become: yes
    become_user: root
    remote_user: vagrant

    tasks:
      - name: Create directory for ssh-keys
        file: state=directory mode=0700 dest=/root/.ssh/

      - name: Adding rsa-key in /root/.ssh/authorized_keys
        copy: src=~/.ssh/id_rsa.pub dest=/root/.ssh/authorized_keys owner=root mode=0600
        ignore_errors: yes

      - name: Checking DNS
        command: host -t A google.com

      - name: Installing tools
        apt: >
          package={{ item }}
          state=present
          update_cache=yes
        with_items:
          - git
          - curl
          - ansible
          - software-properties-common

      - name: Installing docker
        shell: curl -fsSL get.docker.com -o get-docker.sh && chmod +x get-docker.sh && ./get-docker.sh
        
      - name: Installing docker_compose
        shell: curl -SL https://github.com/docker/compose/releases/download/v2.5.0/docker-'uname -s'-'uname -m' -o /usr/bin/docker-compose && chmod +x /usr/bin/docker-compose

      - name: Installing yandex_cloud_components
        shell: curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash

      - name: Add key Hashicorp
        shell: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -

      - name: Add Repository Hashicorp
        shell: apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        
      - name: Installing Packer
        shell: apt-get update && sudo apt-get install packer
      
      - name: Installing Terraform
        shell: apt-get update && sudo apt-get install terraform

      - name: Add the current user to docker group
        user: name=vagrant append=yes groups=docker
